### ISSUE TITLE
SystemUI crashes after "Navring: Make it optional" commit

### ISSUE THREAD

**Issue by luk1337** [AOSB/android_frameworks_base#1]
Logcat:

```
E/AndroidRuntime( 2808): FATAL EXCEPTION: main
E/AndroidRuntime( 2808): Process: com.android.systemui, PID: 2808
E/AndroidRuntime( 2808): java.lang.NullPointerException
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.phone.PhoneStatusBar.updateNavigationBarState(PhoneStatusBar.java:475)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.phone.PhoneStatusBar.makeStatusBarView(PhoneStatusBar.java:710)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.phone.PhoneStatusBar.addStatusBarWindow(PhoneStatusBar.java:2999)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.phone.PhoneStatusBar.createAndAddWindows(PhoneStatusBar.java:2973)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.BaseStatusBar.start(BaseStatusBar.java:385)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.phone.PhoneStatusBar.start(PhoneStatusBar.java:572)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.SystemBars.createStatusBarFromConfig(SystemBars.java:106)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.SystemBars.onNoService(SystemBars.java:58)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.ServiceMonitor.startService(ServiceMonitor.java:228)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.ServiceMonitor.access$000(ServiceMonitor.java:49)
E/AndroidRuntime( 2808):        at com.android.systemui.statusbar.ServiceMonitor$1.handleMessage(ServiceMonitor.java:73)
E/AndroidRuntime( 2808):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2808):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2808):        at android.app.ActivityThread.main(ActivityThread.java:5088)
E/AndroidRuntime( 2808):        at java.lang.reflect.Method.invokeNative(NativeMethod)
E/AndroidRuntime( 2808):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2808):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
E/AndroidRuntime( 2808):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
E/AndroidRuntime( 2808):        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by codex-corp** [comment]
confirmed , i've reverted it from yesterday but not pushed

thanks for report
